### ISSUE TITLE
Deprecated Method error reporting

### ISSUE THREAD

**Issue by videobuff** [iceman101184/ajaxcrud#18]
I have this error , if error reporting is on.

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; ajaxCRUD has a deprecated constructor in /usr/local/lsws/friendlygolf/html/ajaxCRUD.class.php on line 137

Will this issue be adressed ? My know how of php is too limited to solve it myself.

Erik

**Comment by R55BKR** [comment]
Hi @videobuff - did / how did you solve this ajaxCrud issue?

**Comment by videobuff** [comment]
I didn't. So i changed over to witing my own html table.

**Comment by R55BKR** [comment]
Gotcha - cheers!
