### ISSUE TITLE
Define root

### ISSUE THREAD

**Issue by tmblog** [iceman101184/ajaxcrud#9]
Hello I am trying to create a page in the root, so in the class file I set it to 
function ajaxCRUD($item, $db_table, $db_table_pk, $ajaxcrud_root = "http://example.com/app/")

but it's not setting, anywhere I need to change?

Missed the api (!)

**Comment by iceman101184** [comment]
Just use reference path not an absolute URL when instantiating the class.

~Sean

**Comment by tmblog** [comment]
Thank you!
